import { Inter } from "next/font/google";
import {Box, Container} from "@mui/material";
// import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Box
        component='body'
        sx={{
            margin: '0px',
            fontFamily: 'Roboto, sans-serif',
        }}
      >
         {children}
      </Box>
    </html>
  );
}
